-- CreateTable
CREATE TABLE "players" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "birthdate" TIMESTAMP(3) NOT NULL,
    "lenght" INTEGER NOT NULL,
    "weight" INTEGER NOT NULL,
    "jersey" INTEGER NOT NULL,
    "playerImage" TEXT,
    "corners" INTEGER NOT NULL,
    "crossing" INTEGER NOT NULL,
    "dribbling" INTEGER NOT NULL,
    "finishing" INTEGER NOT NULL,
    "firstTouch" INTEGER NOT NULL,
    "freeKickTaking" INTEGER NOT NULL,
    "heading" INTEGER NOT NULL,
    "longShots" INTEGER NOT NULL,
    "longThrows" INTEGER NOT NULL,
    "marking" INTEGER NOT NULL,
    "passing" INTEGER NOT NULL,
    "penaltyTaking" INTEGER NOT NULL,
    "tackling" INTEGER NOT NULL,
    "technique" INTEGER NOT NULL,
    "agression" INTEGER NOT NULL,
    "anticipation" INTEGER NOT NULL,
    "bravery" INTEGER NOT NULL,
    "composure" INTEGER NOT NULL,
    "concentration" INTEGER NOT NULL,
    "decisions" INTEGER NOT NULL,
    "determination" INTEGER NOT NULL,
    "flair" INTEGER NOT NULL,
    "leadership" INTEGER NOT NULL,
    "offTheBall" INTEGER NOT NULL,
    "positioning" INTEGER NOT NULL,
    "teamWork" INTEGER NOT NULL,
    "vision" INTEGER NOT NULL,
    "workRate" INTEGER NOT NULL,
    "acceleration" INTEGER NOT NULL,
    "agility" INTEGER NOT NULL,
    "balance" INTEGER NOT NULL,
    "jumpingReach" INTEGER NOT NULL,
    "naturalFitness" INTEGER NOT NULL,
    "pace" INTEGER NOT NULL,
    "stamina" INTEGER NOT NULL,
    "strenght" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "players_pkey" PRIMARY KEY ("id")
);
